# Generated by Django 3.2.4 on 2021-06-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_bet',
            field=models.IntegerField(default=0, verbose_name='Всего ставок'),
        ),
    ]
