# Generated by Django 3.2.4 on 2021-06-04 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_total_bet'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_stream', models.DateTimeField(auto_now_add=True)),
                ('channel_status', models.CharField(blank=True, choices=[('accept_bets', 'Приём ставок'), ('bets_are_made', 'Ставки сделаны')], max_length=32, null=True, verbose_name='Текущий статус стрима')),
                ('channel_url', models.CharField(default='Ссылка на канал', max_length=42, unique=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streamer_channel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_channel',
            },
        ),
    ]
