# Generated by Django 3.2.4 on 2021-06-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_real_twitch_channel_name_userchannel_channel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchannel',
            name='event_bet_amount',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '400'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700'), ('800', '800'), ('900', '900'), ('1000', '1000')], default='100', max_length=32, verbose_name='Сумма ставок'),
        ),
        migrations.AddField(
            model_name='userchannel',
            name='event_close_bet_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userchannel',
            name='event_finish_accepting_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userchannel',
            name='event_open_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userchannel',
            name='event_result',
            field=models.CharField(blank=True, choices=[('win', 'Победа'), ('lost', 'Поражение'), ('canceled', 'Отменить')], max_length=32, null=True, verbose_name='Результат игры'),
        ),
        migrations.AlterField(
            model_name='userchannel',
            name='channel_status',
            field=models.CharField(blank=True, choices=[('accept_bets', 'Приём ставок'), ('bets_are_made', 'Ставки сделаны'), ('bets_are_closed', 'Ставки не принимаются')], max_length=32, null=True, verbose_name='Текущий статус стрима'),
        ),
    ]
