# Generated by Django 3.2.4 on 2021-06-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userchannel_event_finish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchannel',
            name='channel_status',
            field=models.CharField(blank=True, choices=[('accept_bets', 'Приём ставок'), ('bets_are_made', 'Ставки сделаны'), ('bets_are_closed', 'Ставки не принимаются'), ('bets_in_process', 'Идёт игра')], max_length=32, null=True, verbose_name='Текущий статус стрима'),
        ),
    ]
