# Generated by Django 3.2.4 on 2021-06-04 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentActiveBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_open_date', models.DateTimeField(auto_now_add=True)),
                ('event_status', models.CharField(choices=[('accept_bets', 'Приём ставок'), ('bets_are_made', 'Ставки сделаны')], max_length=32, verbose_name='Текущий статус')),
                ('event_game', models.CharField(choices=[('DOTA 2', 'DOTA 2'), ('CS:GO', 'CS:GO')], max_length=32, verbose_name='Игра')),
                ('event_result', models.CharField(blank=True, choices=[('win', 'Победа'), ('lost', 'Поражение'), ('canceled', 'Отменить')], max_length=32, null=True, verbose_name='Результат игры')),
                ('event_streamer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Стример')),
            ],
            options={
                'db_table': 'current_bets',
            },
        ),
        migrations.CreateModel(
            name='CurrentUserBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_date', models.DateTimeField(auto_now_add=True)),
                ('bet_amount', models.IntegerField(default=0, verbose_name='Сумма ставки')),
                ('event_result', models.CharField(default='Не ресчитано', max_length=32, verbose_name='Результат игры')),
                ('user_bet_type', models.CharField(blank=True, choices=[('win', 'Победа'), ('lost', 'Поражение')], max_length=32, null=True, verbose_name='На что поставил')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_event_bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.currentactivebet')),
            ],
            options={
                'db_table': 'current_active_user_bets',
            },
        ),
    ]
