# Generated by Django 3.2.4 on 2021-06-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentactivebet',
            name='event_bet_amount',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '400'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700'), ('800', '800'), ('900', '900'), ('1000', '1000')], default='100', max_length=32, verbose_name='Сумма ставок'),
        ),
    ]
