# Generated by Django 3.2.4 on 2021-06-04 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userchannel'),
        ('betting', '0003_alter_currentactivebet_event_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentactivebet',
            name='event_streamer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userchannel', verbose_name='Стример'),
        ),
    ]
