# Generated by Django 3.2.4 on 2021-06-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_alter_currentactivebet_event_streamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentactivebet',
            name='envent_finish_taking_bets_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentactivebet',
            name='event_close',
            field=models.BooleanField(default=False),
        ),
    ]
