# Generated by Django 3.2.4 on 2021-06-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0006_auto_20210605_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentactivebet',
            name='event_time_start_game',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
