# Generated by Django 3.2.4 on 2021-06-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0007_currentactivebet_event_time_start_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentactivebet',
            name='event_channel',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
