# Generated by Django 3.2.4 on 2021-06-05 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userchannel_channel_status'),
        ('betting', '0008_currentactivebet_event_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentuserbet',
            name='user_event_bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userchannel'),
        ),
        migrations.DeleteModel(
            name='CurrentActiveBet',
        ),
    ]
