# Generated by Django 3.2.4 on 2021-06-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0011_remove_currentuserbet_event_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentuserbet',
            name='streamer_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
